### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by kealan** [milagro-crypto/milagro-crypto-c#265]
Hi All

We are aware that the build is broken and are in the process of resolving the issue.

Kealan

**Comment by jaromil** [comment]
FTR I'm still using the old version of the cmake build system, waiting to find some time to study the switch. I clearly see why you need a to improve the build system and why this is not easy, because of the way milagro generates files.

What I wonder is if substituting `cmake` with `meson` and `ninja` could help: the latter is inherently designed to provide two build stages, while keeping very simple and somehow similar to makefiles.

**Comment by kealan** [comment]
I think that the refactored cmake build is really very good. The issues I think that we need to address is the Makefile on top of cmake which is very confusing. 

BTW the build is now passing.
