### ISSUE TITLE
Contribution/release workflow

### ISSUE THREAD

**Issue by VMitov** [milagro-crypto/milagro-crypto-c#271]
I was wondering are there any benefits of this feature-branch -> develop -> master approach that we can't get from simple feature-branch -> Marge request -> master?  Lately we do many one commit releases and currently it is a hassle. If we in the future need, we can still have long living branches (which is highly discouraged but possible) and when they are ready we can merge in master. 

I'm suggesting the following changes. 
- delete 'develop', make 'master' default branch. 
- all merge request are towards master
- we remove REVISION and VERSION files, when we want to release we push git tag

**Comment by drbild** [comment]
#### Branch Structure
I'm in favor of dropping `develop` and making `master` the default branch.

The separate `develop` and `master` branches are useful if `master` is intended to always be releasable (and if fact, maybe its tip is always a release).  Accepted PRs are merged to `develop`, but additional testing (via `-rc` releases or a slow-moving CI process) is done before `develop` is merged to `master`. I don't think that sort of process is useful here.

#### Release Process
There's a second concern proposed here too --- how releases are managed.

Currently, the version number is bumped as part of each merge to master.  This is probably too aggressive.  I suggest bumping the version number as part of an explicit release commit.  This decouples the merge and release processes. Each merge doesn't require a release commit; releases can be issued when it seems appropriate.

Dropping the `REVISION` file seems fine. (I don't think it is used???)

I'm against dropping the `VERSION` file.  Git tags aren't part of the commit history (they can be deleted, recreated against a different commit, etc.) and don't exist in the working tree.  I think it's important for the version to be recorded in a file whose changes appear in the Git history.  Otherwise all that version information can be accidentally lost by deleted the tags.

With this suggestion, the release process then consists simply of updating the `VERSION` file and tagging that commit with the new version number.

**Comment by VMitov** [comment]
Hey @drbild, thank you for your feedback. 
Technically we can protect the tags from deletion but I can agree on keeping the VERSION file. I simplified it to the maximum but you are bringing valid arguments.

PS: I meant 'RELEASE' and not 'REVISION', but yes - it seems it is not used.

**Comment by drbild** [comment]
> I meant 'RELEASE' and not 'REVISION'

Oops, me too!
